# Generated by Django 4.0.10 on 2024-08-19 13:40

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
