# Generated by Django 4.0.10 on 2024-08-19 14:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
